//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lua.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lua_parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILuaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LuaBaseListener : ILuaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] LuaParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] LuaParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nonaugmented_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonaugmented_start([NotNull] LuaParser.Nonaugmented_startContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nonaugmented_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonaugmented_start([NotNull] LuaParser.Nonaugmented_startContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_list_of_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_list_of_stat([NotNull] LuaParser.Nempty_list_of_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_list_of_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_list_of_stat([NotNull] LuaParser.Nempty_list_of_statContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_list_of_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_list_of_stat([NotNull] LuaParser.Allow_empty_list_of_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_list_of_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_list_of_stat([NotNull] LuaParser.Allow_empty_list_of_statContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.list_of_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_of_stat([NotNull] LuaParser.List_of_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.list_of_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_of_stat([NotNull] LuaParser.List_of_statContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.optional_retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_retstat([NotNull] LuaParser.Optional_retstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.optional_retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_retstat([NotNull] LuaParser.Optional_retstatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] LuaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] LuaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.optional_semicol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_semicol([NotNull] LuaParser.Optional_semicolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.optional_semicol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_semicol([NotNull] LuaParser.Optional_semicolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstat([NotNull] LuaParser.RetstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstat([NotNull] LuaParser.RetstatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_list_of_elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_list_of_elseif([NotNull] LuaParser.Nempty_list_of_elseifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_list_of_elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_list_of_elseif([NotNull] LuaParser.Nempty_list_of_elseifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_list_of_elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_list_of_elseif([NotNull] LuaParser.Allow_empty_list_of_elseifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_list_of_elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_list_of_elseif([NotNull] LuaParser.Allow_empty_list_of_elseifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.list_of_elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_of_elseif([NotNull] LuaParser.List_of_elseifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.list_of_elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_of_elseif([NotNull] LuaParser.List_of_elseifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.optional_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_else([NotNull] LuaParser.Optional_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.optional_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_else([NotNull] LuaParser.Optional_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] LuaParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] LuaParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_assign_rhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_assign_rhs([NotNull] LuaParser.Opt_assign_rhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_assign_rhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_assign_rhs([NotNull] LuaParser.Opt_assign_rhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] LuaParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] LuaParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.range_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_tail([NotNull] LuaParser.Range_tailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.range_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_tail([NotNull] LuaParser.Range_tailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseif([NotNull] LuaParser.ElseifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseif([NotNull] LuaParser.ElseifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.else_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_block([NotNull] LuaParser.Else_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.else_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_block([NotNull] LuaParser.Else_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] LuaParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] LuaParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinexp([NotNull] LuaParser.BinexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinexp([NotNull] LuaParser.BinexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinseq([NotNull] LuaParser.BinseqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinseq([NotNull] LuaParser.BinseqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binoperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinoperand([NotNull] LuaParser.BinoperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binoperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinoperand([NotNull] LuaParser.BinoperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.unaryexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryexp([NotNull] LuaParser.UnaryexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.unaryexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryexp([NotNull] LuaParser.UnaryexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponent([NotNull] LuaParser.ExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponent([NotNull] LuaParser.ExponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] LuaParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] LuaParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nonempty_seplist_of_comma_and_exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonempty_seplist_of_comma_and_exp([NotNull] LuaParser.Nonempty_seplist_of_comma_and_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nonempty_seplist_of_comma_and_exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonempty_seplist_of_comma_and_exp([NotNull] LuaParser.Nonempty_seplist_of_comma_and_expContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nonempty_seplist_of_comma_and_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nonempty_seplist_of_comma_and_exp_p_([NotNull] LuaParser.Allow_empty_o_nonempty_seplist_of_comma_and_exp_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nonempty_seplist_of_comma_and_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nonempty_seplist_of_comma_and_exp_p_([NotNull] LuaParser.Allow_empty_o_nonempty_seplist_of_comma_and_exp_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.seplist_of_comma_and_exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeplist_of_comma_and_exp([NotNull] LuaParser.Seplist_of_comma_and_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.seplist_of_comma_and_exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeplist_of_comma_and_exp([NotNull] LuaParser.Seplist_of_comma_and_expContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] LuaParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] LuaParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.optional_funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_funcname([NotNull] LuaParser.Optional_funcnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.optional_funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_funcname([NotNull] LuaParser.Optional_funcnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.optional_parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_parlist([NotNull] LuaParser.Optional_parlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.optional_parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_parlist([NotNull] LuaParser.Optional_parlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] LuaParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] LuaParser.FuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varargs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarargs([NotNull] LuaParser.VarargsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varargs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarargs([NotNull] LuaParser.VarargsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_of_comma_and_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_of_comma_and_name([NotNull] LuaParser.Nempty_seplist_of_comma_and_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_of_comma_and_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_of_comma_and_name([NotNull] LuaParser.Nempty_seplist_of_comma_and_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParlist([NotNull] LuaParser.ParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParlist([NotNull] LuaParser.ParlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_fields([NotNull] LuaParser.Nempty_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_fields([NotNull] LuaParser.Nempty_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_fields([NotNull] LuaParser.Allow_empty_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_fields([NotNull] LuaParser.Allow_empty_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_list([NotNull] LuaParser.Field_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_list([NotNull] LuaParser.Field_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.optional_fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_fieldsep([NotNull] LuaParser.Optional_fieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.optional_fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_fieldsep([NotNull] LuaParser.Optional_fieldsepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] LuaParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] LuaParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsep([NotNull] LuaParser.FieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsep([NotNull] LuaParser.FieldsepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinop([NotNull] LuaParser.BinopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinop([NotNull] LuaParser.BinopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace lua_parser
